"""Generate docs/marketing/hook-database.md from marketing/hooks.json.

hooks.json is the single source of truth (the Poster reads it; tests gate
it). This script renders the human swipe file. Run after editing the JSON:

    python marketing/gen_hook_doc.py            # write the doc
    python marketing/gen_hook_doc.py --check    # CI: fail if doc is stale
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent
HOOKS = ROOT / "hooks.json"
DOC = ROOT.parent / "docs" / "marketing" / "hook-database.md"

PILLAR_TITLES = {
    "deals": "Deals (price drops · closing soon · cheapest · EMD)",
    "risk": "Risk & what the price does not cover (the warning format)",
    "market_data": "Market data (our graph, nobody else has it)",
    "education": "Education (3-ring syllabus)",
    "news": "Real-estate & policy news (+ our auction tie-in)",
    "geo": "Geo spotlights (city / area / corridor)",
    "evaluation": "Evaluation walkthroughs (the product demo as content)",
    "qa": "Q&A (real user questions, anonymised)",
    "build_in_public": "Build in public (founder journey)",
}


def render() -> str:
    data = json.loads(HOOKS.read_text(encoding="utf-8"))
    b = data["budgets"]
    lines = [
        "# AuctionScope — Hook Database",
        "",
        "*GENERATED from `marketing/hooks.json` — edit the JSON, then run "
        "`python marketing/gen_hook_doc.py`. Do not edit this file by hand.*",
        "",
        "One entry = one hook **concept** on three surfaces: the **caption** "
        f"(post line 1, ≤{b['caption']} chars), the **reel first frame** "
        f"(line1 ≤{b['reel_line1']} / line2 ≤{b['reel_line2']} chars), and the "
        f"**card headline** (≤{b['headline']} chars). `{{placeholders}}` are "
        "filled only from real auction/graph fields — the honesty rule applies "
        "to every string. The Poster injects the relevant pillar's entries into "
        "its prompt as the HOOK ARSENAL; humans swipe from here when posting "
        "manually.",
        "",
        f"Mechanisms (copy-playbook.md Part 1): {' · '.join(data['mechanisms'])}",
        "",
    ]
    total = 0
    for pillar, hooks in data["pillars"].items():
        total += len(hooks)
        lines += [f"## {PILLAR_TITLES.get(pillar, pillar)} — {len(hooks)} hooks", ""]
        lines += ["| # | mechanism | caption (post line 1) | reel first frame | card headline |",
                  "|---|---|---|---|---|"]
        for i, h in enumerate(hooks, 1):
            reel = f"{h['reel']['line1']} / {h['reel']['line2']}"
            cap = h["caption"].replace("|", "\\|")
            lines.append(f"| {i} | `{h['mechanism']}` | {cap} | {reel} | {h['headline']} |")
        lines.append("")
    lines += [f"**{total} hooks across {len(data['pillars'])} pillars.**", ""]
    return "\n".join(lines)


def main() -> None:
    out = render()
    if "--check" in sys.argv:
        current = DOC.read_text(encoding="utf-8") if DOC.exists() else ""
        if current != out:
            sys.exit("hook-database.md is stale — run: python marketing/gen_hook_doc.py")
        print("hook-database.md is in sync")
        return
    DOC.write_text(out, encoding="utf-8")
    print(f"wrote {DOC}")


if __name__ == "__main__":
    main()
